# The program to run
program: color_syncnet_train_sweep.py
command:
  - "--config_file=/data/zhanglingling/AI/Wav2Lip/configs/config_syncnet.yaml"
  - "--data_root=/data/dh_dataset/lrs2_v1/mvlrs_v1/main_processed"
  - "--checkpoint_dir=/data/zhanglingling/AI/Wav2Lip/checkpoints/syncnet_sweep"
  - "--checkpoint_path=null"

# Project this sweep is part of
project: wav2lip
entity: lingz0124
# Mathod to be grid, random or bayes
method: bayes

# Metric to optimize
metric:
  name: eval/loss
  goal: minimize

# Parameters space to search 
parameters:
  syncnet_lr:
    distribution: log_uniform_values
    max: 0.001
    min: 0.00001
  syncnet_batch_size:
    values: [32, 64, 128]
    
# early termination 
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2

# global stop condition
stop:
  max_runs: 50

